# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kevin's website
email: crowekevin5@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is my first site. It is a work in progress. I hope you enjoy it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: n/a
github_username:  kcrowe234

# Build settings
markdown: kramdown
